#!/usr/bin/env bash
set -euo pipefail

# Configuration
BRANCH="automation/blog-post-publisher-job10"
FILE_PATH="src/data/blog/building-self-improving-automation-pipeline-job10.md"
COMMIT_MESSAGE="feat(blog): publish Building a Self-Improving Automation Pipeline: Lessons from Job #10"
ARTIFACT_DIR="automation/runs/job10"
PR_TITLE="Blog: Building a Self-Improving Automation Pipeline: Lessons from Job #10"
PR_BODY="Automated blog post about the automation system itself - a self-referential automation pipeline.

## Changes
- New blog post: \`building-self-improving-automation-pipeline-job10.md\`
- Automation artifacts in \`automation/runs/job10/\`

## Content Summary
This post discusses building a self-improving automation pipeline with GitHub CLI integration, covering lessons learned from Job #10 implementation.

## Automation Details
- Job ID: job10 (repurposed)
- Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
- Type: Meta-automation (automation about automation)

## Review Notes
This post was generated by the automation system it describes - a self-referential example of portfolio automation."

echo "🚀 Starting automated blog post publication..."
echo "=============================================="

# Step 1: Create/checkout branch
echo "📋 Step 1: Setting up Git branch..."
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# Step 2: Add files
echo "📋 Step 2: Staging changes..."
git add "$FILE_PATH" "$ARTIFACT_DIR"

# Step 3: Commit
echo "📋 Step 3: Committing changes..."
if git commit -m "$COMMIT_MESSAGE" --no-verify; then
    echo "✅ Commit successful"
else
    echo "⚠️  Commit failed (maybe no changes?)"
    # Check if there are actually changes
    if git diff --cached --quiet; then
        echo "❌ No changes to commit. Exiting."
        exit 1
    fi
fi

# Step 4: Push to origin
echo "📋 Step 4: Pushing to remote..."
if git push -u origin "$BRANCH"; then
    echo "✅ Push successful"
else
    echo "❌ Push failed. Check remote configuration."
    exit 1
fi

# Step 5: Create Pull Request with gh
echo "📋 Step 5: Creating Pull Request..."
echo "PR Title: $PR_TITLE"
echo "PR Body length: ${#PR_BODY} characters"

if command -v gh >/dev/null 2>&1; then
    echo "✅ GitHub CLI detected, creating PR..."
    
    # Create PR
    PR_RESULT=$(gh pr create         --title "$PR_TITLE"         --body "$PR_BODY"         --base main         --head "$BRANCH"         --label "automation,blog,meta"         2>&1)
    
    if [ $? -eq 0 ]; then
        echo "🎉 Pull Request created successfully!"
        echo "🔗 PR URL: $PR_RESULT"
        
        # Try to get the PR number
        PR_NUMBER=$(echo "$PR_RESULT" | grep -oE '[0-9]+' | tail -1)
        if [ -n "$PR_NUMBER" ]; then
            echo "📝 PR Number: $PR_NUMBER"
            
            # Create a PR reference file
            echo "{"pr_number": $PR_NUMBER, "pr_url": "$PR_RESULT", "created_at": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"}" > "$ARTIFACT_DIR/pr-reference.json"
            echo "✅ Created PR reference file: $ARTIFACT_DIR/pr-reference.json"
        fi
    else
        echo "⚠️  PR creation failed: $PR_RESULT"
        echo "You can manually create a PR at: https://github.com/$(git remote get-url origin | sed -E 's/.*github.com[:\/]//' | sed 's/\.git$//')/compare/main...$BRANCH"
    fi
else
    echo "⚠️  GitHub CLI (gh) not found. Skipping PR creation."
    echo "📋 Manual PR creation required:"
    echo "   Visit: https://github.com/$(git remote get-url origin | sed -E 's/.*github.com[:\/]//' | sed 's/\.git$//')/compare/main...$BRANCH"
    echo "   Title: $PR_TITLE"
    echo "   Body: $PR_BODY"
fi

echo ""
echo "=============================================="
echo "✅ Publication pipeline complete!"
echo "📁 Artifacts in: $ARTIFACT_DIR"
echo "🌐 Branch: $BRANCH"
if [ -f "$ARTIFACT_DIR/pr-reference.json" ]; then
    echo "🔗 PR created: $(cat "$ARTIFACT_DIR/pr-reference.json" | grep -o '"pr_url":"[^"]*"' | cut -d'"' -f4)"
fi
